/*
 * AppConstants
 * These are the variables that determine what our central data store (reducer.js)
 * changes in our state. When you add a new action, you have to add a new constant here
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'YOUR_ACTION_CONSTANT';
 */
export const CHANGE_FORM = 'CHANGE_FORM';
export const CHANGE_REGISTER_FORM = 'CHANGE_REGISTER_FORM';
export const SET_AUTH = 'SET_AUTH';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_RESPONSE = 'SET_RESPONSE';
export const NOTIFICATION = 'NOTIFICATION';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const CHECK_TOKEN_REQUEST = 'CHECK_TOKEN_REQUEST';
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS';
export const CHECK_TOKEN_FAILURE = 'CHECK_TOKEN_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const VERIFY_FAILURE = 'VERIFY_FAILURE';
export const REQUEST_EMAIL = 'REQUEST_EMAIL';

export const SET_PROJECT_ID = 'SET_PROJECT_ID';
export const RESIZE_SCREEN = 'RESIZE_SCREEN';

export const REMOVE_ERROR = 'REMOVE_ERROR';

export const SEARCH_ACCOUNT_REQUEST = 'SEARCH_ACCOUNT_REQUEST';
export const SEARCH_ACCOUNT_SUCCESS = 'SEARCH_ACCOUNT_SUCCESS';
export const SEARCH_ACCOUNT_FAILURE = 'SEARCH_ACCOUNT_FAILURE';

export const REGISTER_MEMBER_REQUEST = 'REGISTER_MEMBER_REQUEST';
export const REGISTER_MEMBER_SUCCESS = 'REGISTER_MEMBER_SUCCESS';
export const REGISTER_MEMBER_FAILURE = 'REGISTER_MEMBER_FAILURE';