export const DEFAULT_INFRA_STATE = 'DEFAULT_INFRA_STATE';
export const CHANGE_KUBE_FORM = 'CHANGE_KUBE_FORM';
export const HANDLE_REMOVE_KUBE = 'HANDLE_REMOVE_KUBE';
export const HANDLE_ADD_NEW_KUBE = 'HANDLE_ADD_NEW_KUBE';
export const CHANGE_NEW_KUBE_FORM = 'CHANGE_NEW_KUBE_FORM';
export const KUBE_ERROR = 'KUBE_ERROR';
export const DELETED_INFRASTURCTURE = 'DELETED_INFRASTURCTURE';
export const CHANGE_SELECTED_INFRA = 'CHANGE_SELECTED_INFRA';

export const GET_INFRA_REQUEST = 'GET_INFRA_REQUEST';
export const GET_INFRA_SUCCESS = 'GET_INFRA_SUCCESS';
export const GET_INFRA_FAILURE = 'GET_INFRA_FAILURE';

export const REPO_ID_REQUEST = 'REPO_ID_REQUEST';
export const REPO_ID_SUCCESS = 'REPO_ID_SUCCESS';
export const REPO_ID_FAILURE = 'REPO_ID_FAILURE';

export const ADD_EXISTING_KUBE_REQUEST = 'ADD_EXISTING_KUBE_REQUEST';
export const ADD_EXISTING_KUBE_SUCCESS = 'ADD_EXISTING_KUBE_SUCCESS';
export const ADD_EXISTING_KUBE_FAILURE = 'ADD_EXISTING_KUBE_FAILURE';

export const CREATE_INVENTORY_REQUEST = 'CREATE_INVENTORY_REQUEST';
export const CREATE_INVENTORY_SUCCESS = 'CREATE_INVENTORY_SUCCESS';
export const CREATE_INVENTORY_FAILURE = 'CREATE_INVENTORY_FAILURE';

export const CREATE_TEMPLATE_REQUEST = 'CREATE_TEMPLATE_REQUEST';
export const CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS';
export const CREATE_TEMPLATE_FAILURE = 'CREATE_TEMPLATE_FAILURE';

export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';

export const AKIRA_KUBE_REQUEST = 'AKIRA_KUBE_REQUEST';
export const AKIRA_KUBE_SUCCESS = 'AKIRA_KUBE_SUCCESS';
export const AKIRA_KUBE_FAILURE = 'AKIRA_KUBE_FAILURE';

export const DELETE_INFRA_REQUEST = 'DELETE_INFRA_REQUEST';
export const DELETE_INFRA_SUCCESS = 'DELETE_INFRA_SUCCESS';
export const DELETE_INFRA_FAILURE = 'DELETE_INFRA_FAILURE';