export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM';
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const DEFAULT_LOGIN_STATE = 'DEFAULT_LOGIN_STATE';
export const LOGIN_FROM_REDIRECT = 'LOGIN_FROM_REDIRECT';

export const WORKSPACE_NAME_REQUEST = 'WORKSPACE_NAME_REQUEST';
export const WORKSPACE_NAME_SUCCESS = 'WORKSPACE_NAME_SUCCESS';
export const WORKSPACE_NAME_FAILURE = 'WORKSPACE_NAME_FAILURE';

export const CHECK_SESSION_REQUEST = 'CHECK_SESSION_REQUEST';
export const CHECK_SESSION_SUCCESS = 'CHECK_SESSION_SUCCESS';
export const CHECK_SESSION_FAILURE = 'CHECK_SESSION_FAILURE';

export const MEMBER_REGISTRATION_REQUEST = 'MEMBER_REGISTRATION_REQUEST';
export const MEMBER_REGISTRATION_SUCCESS = 'MEMBER_REGISTRATION_SUCCESS';
export const MEMBER_REGISTRATION_FAILURE = 'MEMBER_REGISTRATION_FAILURE';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';
