export const MODEL_CATEGORY_REQUEST = 'MODEL_CATEGORY_REQUEST';
export const MODEL_CATEGORY_SUCCESS = 'MODEL_CATEGORY_SUCCESS';
export const MODEL_CATEGORY_FAILURE = 'MODEL_CATEGORY_FAILURE';

export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const FILTER_BY_REPO = 'FILTER_BY_REPO';
export const SORTED_BY = 'SORTED_BY';
export const CHANGE_SEARCH_QUERY = 'CHANGE_SEARCH_QUERY';
export const CHANGE_MARKETPLACE_FORM = 'CHANGE_MARKETPLACE_FORM';
export const DEFAULT_MARKETPLACE_STATE = 'DEFAULT_MARKETPLACE_STATE';

export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE';
export const PREDICT_IMAGE_UPLOAD_SUCCESS = 'PREDICT_IMAGE_UPLOAD_SUCCESS';

export const SUBMIT_MARKETPLACE_REQUEST = 'SUBMIT_MARKETPLACE_REQUEST';
export const SUBMIT_MARKETPLACE_SUCCESS = 'SUBMIT_MARKETPLACE_SUCCESS';
export const SUBMIT_MARKETPLACE_FAILURE = 'SUBMIT_MARKETPLACE_FAILURE';

export const ALL_MODEL_REQUEST = 'ALL_MODEL_REQUEST';
export const ALL_MODEL_SUCCESS = 'ALL_MODEL_SUCCESS';
export const ALL_MODEL_FAILURE = 'ALL_MODEL_FAILURE';

export const MODEL_DETAIL_REQUEST = 'MODEL_DETAIL_REQUEST';
export const MODEL_DETAIL_SUCCESS = 'MODEL_DETAIL_SUCCESS';
export const MODEL_DETAIL_FAILURE = 'MODEL_DETAIL_FAILURE';

export const RUN_MODEL_REQUEST = 'RUN_MODEL_REQUEST';
export const RUN_MODEL_SUCCESS = 'RUN_MODEL_SUCCESS';
export const RUN_MODEL_FAILURE = 'RUN_MODEL_FAILURE';

export const MARKETPLACE_INPUT_CODE_DATA = 'MARKETPLACE_INPUT_CODE_DATA';
