export const SUBMIT_CREDS = 'SUBMIT_CREDS';
export const CHANGE_SESSION = 'CHANGE_SESSION';
export const DEFAULT_PROJECT_STATE = 'DEFAULT_PROJECT_STATE';
export const CHANGE_PROJECT_FORM = 'CHANGE_PROJECT_FORM';
export const CHANGE_MEMBER_FORM = 'CHANGE_MEMBER_FORM';
export const CHANGE_PROJECT_SESSION = 'CHANGE_PROJECT_SESSION';
export const DELETED_PROJECT = 'DELETED_PROJECT';
export const DELETED_PROJECT_MEMBER = 'DELETED_PROJECT_MEMBER';
export const HANDLE_ADD_NEW_MEMBER = 'HANDLE_ADD_NEW_MEMBER';
export const HANDLE_REMOVE_MEMBER = 'HANDLE_REMOVE_MEMBER';

export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE';

export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

export const PROJECT_MEMBERS_REQUEST = 'PROJECT_MEMBERS_REQUEST';
export const PROJECT_MEMBERS_SUCCESS = 'PROJECT_MEMBERS_SUCCESS';
export const PROJECT_MEMBERS_FAILURE = 'PROJECT_MEMBERS_FAILURE';

export const DELETE_PROJECT_MEMBER_REQUEST = 'DELETE_PROJECT_MEMBER_REQUEST';
export const DELETE_PROJECT_MEMBER_SUCCESS = 'DELETE_PROJECT_MEMBER_SUCCESS';
export const DELETE_PROJECT_MEMBER_FAILURE = 'DELETE_PROJECT_MEMBER_FAILURE';

export const ADD_PROJECT_MEMBER_REQUEST = 'ADD_PROJECT_MEMBER_REQUEST';
export const ADD_PROJECT_MEMBER_SUCCESS = 'ADD_PROJECT_MEMBER_SUCCESS';
export const ADD_PROJECT_MEMBER_FAILURE = 'ADD_PROJECT_MEMBER_FAILURE';

export const GET_DEFAULT_PROJECTS_REQUEST = 'GET_DEFAULT_PROJECTS_REQUEST';
export const GET_DEFAULT_PROJECTS_SUCCESS = 'GET_DEFAULT_PROJECTS_SUCCESS';
export const GET_DEFAULT_PROJECTS_FAILURE = 'GET_DEFAULT_PROJECTS_FAILURE';
