export const UPDATE_RESOURCE_LIST = 'UPDATE_RESOURCE_LIST';
export const CHANGE_RESOURCE_SEARCH = 'CHANGE_RESOURCE_SEARCH';
export const DEFAULT_RESOURCE_STATE = 'DEFAULT_RESOURCE_STATE';

export const ALL_RESOURCE_REQUEST = 'ALL_RESOURCE_REQUEST';
export const ALL_RESOURCE_SUCCESS = 'ALL_RESOURCE_SUCCESS';
export const ALL_RESOURCE_FAILURE = 'ALL_RESOURCE_FAILURE';

export const DEPLOY_RESOURCE_REQUEST = 'DEPLOY_RESOURCE_REQUEST';
export const DEPLOY_RESOURCE_SUCCESS = 'DEPLOY_RESOURCE_SUCCESS';
export const DEPLOY_RESOURCE_FAILURE = 'DEPLOY_RESOURCE_FAILURE';

