/**
 * Created by amir on 31/7/17.
 */
export const CHANGE_ROLE_PAGE = 'CHANGE_ROLE_PAGE';
export const GET_ROLES_LIST_REQUEST = 'GET_ROLES_LIST_REQUEST';
export const GET_ROLES_LIST_SUCCESS = 'GET_ROLES_LIST_SUCCESS';
export const GET_ROLES_LIST_FAILURE = 'GET_ROLES_LIST_FAILURE';
export const NEW_ROLES_LIST = 'NEW_ROLES_LIST';
export const CHANGE_ROLE_PAGE_RANGE = 'CHANGE_ROLE_PAGE_RANGE';

