/**
 * Created by amir on 27/7/17.
 */

export const CHANGE_USER_PAGE = 'CHANGE_USER_PAGE';
export const GET_USER_LIST_REQUEST = 'GET_USER_LIST_REQUEST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE';
export const NEW_USER_LIST = 'NEW_USER_LIST';
export const CHANGE_USER_PAGE_RANGE = 'CHANGE_USER_PAGE_RANGE';
export const REMOVE_MEMBER_INVITE = 'REMOVE_MEMBER_INVITE';
export const ADD_MEMBER_INVITE = 'ADD_MEMBER_INVITE';
export const INVITE_MEMBER_REQUEST = 'INVITE_MEMBER_REQUEST';
export const INVITE_MEMBER_SUCCESS = 'INVITE_MEMBER_SUCCESS';
export const INVITE_MEMBER_FAILURE = 'INVITE_MEMBER_FAILURE';
export const DEFAULT_USER_STATE = 'DEFAULT_USER_STATE';


export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'ET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE =  'GET_USER_PROFILE_FAILURE'
