/**
 * Created by Makan Singh on 20/05/19.
 */

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'ET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE =  'GET_USER_PROFILE_FAILURE'

export const HANDLE_ADD_MORE_MEMBER = 'HANDLE_ADD_MORE_MEMBER';
export const ADD_WORKSPACE_MEMBER_REQUEST = 'ADD_WORKSPACE_MEMBER_REQUEST';
export const ADD_WORKSPACE_MEMBER_SUCCESS = 'ADD_WORKSPACE_MEMBER_SUCCESS';
export const ADD_WORKSPACE_MEMBER_FAILURE = 'ADD_WORKSPACE_MEMBER_FAILURE';

export const GET_WORKSPACE_MEMBER_LIST_REQUEST = 'GET_WORKSPACE_MEMBER_LIST_REQUEST';
export const GET_WORKSPACE_MEMBER_LIST_SUCCESS = 'GET_WORKSPACE_MEMBER_LIST_SUCCESS';
export const GET_WORKSPACE_MEMBER_LIST_FAILURE = 'GET_WORKSPACE_MEMBER_LIST_FAILURE';
export const CLEAR_MEMBER_DATA = 'CLEAR_MEMBER_DATA';
export const HANDLE_REMOVE_WORKSPACE_MEMBER = 'HANDLE_REMOVE_WORKSPACE_MEMBER';
export const HANDLE_UPDATE_MEMBER_LIST = 'HANDLE_UPDATE_MEMBER_LIST';
