export const DEFAULT_WORKBENCH_STATE = 'DEFAULT_WORKBENCH_STATE';
export const CHANGE_WORKBENCH_FORM = 'CHANGE_WORKBENCH_FORM';
export const UPDATE_WORKBENCH_LIST = 'UPDATE_WORKBENCH_LIST';
export const DELETED_WORKBENCH = 'DELETED_WORKBENCH';

export const CREATE_WORKBENCH_REQUEST = 'CREATE_WORKBENCH_REQUEST';
export const CREATE_WORKBENCH_SUCCESS = 'CREATE_WORKBENCH_SUCCESS';
export const CREATE_WORKBENCH_FAILURE = 'CREATE_WORKBENCH_FAILURE';

export const ALL_WORKBENCH_REQUEST = 'ALL_WORKBENCH_REQUEST';
export const ALL_WORKBENCH_SUCCESS = 'ALL_WORKBENCH_SUCCESS';
export const ALL_WORKBENCH_FAILURE = 'ALL_WORKBENCH_FAILURE';

export const DEPLOYED_WORKBENCH_REQUEST = 'DEPLOYED_WORKBENCH_REQUEST';
export const DEPLOYED_WORKBENCH_SUCCESS = 'DEPLOYED_WORKBENCH_SUCCESS';
export const DEPLOYED_WORKBENCH_FAILURE = 'DEPLOYED_WORKBENCH_FAILURE';

export const DELETE_WORKBENCH_REQUEST = 'DELETE_WORKBENCH_REQUEST';
export const DELETE_WORKBENCH_SUCCESS = 'DELETE_WORKBENCH_SUCCESS';
export const DELETE_WORKBENCH_FAILURE = 'DELETE_WORKBENCH_FAILURE';

export const UPDATE_CREATE_WORKBENCH_DATA = 'UPDATE_CREATE_WORKBENCH_DATA'

export const GET_WORKBENCH_INGRESS_REQUEST = 'GET_WORKBENCH_INGRESS_REQUEST';
export const GET_WORKBENCH_INGRESS_SUCCESS = 'GET_WORKBENCH_INGRESS_SUCCESS';
export const GET_WORKBENCH_INGRESS_FAILURE = 'GET_WORKBENCH_INGRESS_FAILURE';

// mlflow dashboard constants
export const FETCH_SLECTED_WORKBECNH_NAME = 'FETCH_SLECTED_WORKBECNH_NAME';
