export const DRAWER_TOGGELE_HANDDLE = 'DRAWER_TOGGELE_HANDDLE';
export const HANDLE_DASHBOARD_TYPE = 'HANDLE_DASHBOARD_TYPE';
export const DASHBOARD_CONTENT_LAYOUT_TYPE = 'DASHBOARD_CONTENT_LAYOUT_TYPE';
